spring.application.name=talex
server.servlet.context-path=/api/v1

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/talex
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


jwt.secret=${SPRING_JWT_SECRET}