INSERT INTO skill (name, category) VALUES
                                       ('Java', 'Programming'),
                                       ('Spring Boot', 'Programming'),
                                       ('Hibernate', 'Programming'),
                                       ('JPA', 'Programming'),
                                       ('Python', 'Programming'),
                                       ('C++', 'Programming'),
                                       ('C#', 'Programming'),
                                       ('JavaScript', 'Programming'),
                                       ('TypeScript', 'Programming'),
                                       ('Go', 'Programming'),
                                       ('Rust', 'Programming'),
                                       ('PHP', 'Programming'),

                                       ('React', 'Frontend'),
                                       ('Next.js', 'Frontend'),
                                       ('Angular', 'Frontend'),
                                       ('Vue.js', 'Frontend'),
                                       ('HTML', 'Frontend'),
                                       ('CSS', 'Frontend'),
                                       ('Tailwind CSS', 'Frontend'),
                                       ('Bootstrap', 'Frontend'),

                                       ('Node.js', 'Backend'),
                                       ('Express.js', 'Backend'),
                                       ('NestJS', 'Backend'),
                                       ('ASP.NET', 'Backend'),
                                       ('Django', 'Backend'),
                                       ('Flask', 'Backend'),
                                       ('FastAPI', 'Backend'),

                                       ('PostgreSQL', 'Database'),
                                       ('MySQL', 'Database'),
                                       ('MongoDB', 'Database'),
                                       ('Redis', 'Database'),
                                       ('Oracle Database', 'Database'),
                                       ('SQL Server', 'Database'),

                                       ('Docker', 'DevOps'),
                                       ('Kubernetes', 'DevOps'),
                                       ('Jenkins', 'DevOps'),
                                       ('GitHub Actions', 'DevOps'),
                                       ('Terraform', 'DevOps'),
                                       ('Ansible', 'DevOps'),
                                       ('Linux', 'DevOps'),

                                       ('AWS', 'Cloud'),
                                       ('Azure', 'Cloud'),
                                       ('Google Cloud', 'Cloud'),

                                       ('Git', 'Tools'),
                                       ('Postman', 'Tools'),
                                       ('Swagger', 'Tools'),
                                       ('Figma', 'Tools'),

                                       ('Machine Learning', 'AI'),
                                       ('Deep Learning', 'AI'),
                                       ('TensorFlow', 'AI'),
                                       ('PyTorch', 'AI'),
                                       ('OpenAI API', 'AI'),
                                       ('Computer Vision', 'AI'),
                                       ('Natural Language Processing', 'AI'),

                                       ('UI Design', 'Design'),
                                       ('UX Design', 'Design'),
                                       ('Graphic Design', 'Design'),
                                       ('Adobe Photoshop', 'Design'),
                                       ('Adobe Illustrator', 'Design'),

                                       ('Project Management', 'Business'),
                                       ('Agile', 'Business'),
                                       ('Scrum', 'Business'),
                                       ('Business Analysis', 'Business'),

                                       ('Content Writing', 'Marketing'),
                                       ('SEO', 'Marketing'),
                                       ('Digital Marketing', 'Marketing'),
                                       ('Social Media Marketing', 'Marketing'),

                                       ('Photography', 'Creative'),
                                       ('Video Editing', 'Creative'),
                                       ('Adobe Premiere Pro', 'Creative'),
                                       ('After Effects', 'Creative'),

                                       ('Excel', 'Office'),
                                       ('Power BI', 'Office'),
                                       ('Data Analysis', 'Office'),
                                       ('Tableau', 'Office');